In [1]:
import inceptionv3Cutie
import torch
import torch.nn.functional as F


In [2]:
# inceptionv3 BasicConv2d
inceptionv3Cutie.BasicConv2d(3, 32, kernel_size=3, stride=2)

BasicConv2d(
  (conv): Conv2d(3, 32, kernel_size=(3, 3), stride=(2, 2), bias=False)
  (bn): BatchNorm2d(32, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
)

In [3]:
# testing BasicConv2d 
# depth, height, width
# 3 x 299 x 299
tensor = torch.rand(3, 299, 299)
conv2d = inceptionv3Cutie.BasicConv2d(3, 32, kernel_size=3, stride=2)
conv2d = conv2d(tensor.clone().unsqueeze(0))
print(conv2d)

tensor([[[[0.0000, 0.0873, 0.0000,  ..., 1.4082, 0.0000, 0.0000],
          [0.9221, 1.7712, 0.0000,  ..., 0.0000, 0.0000, 0.3173],
          [0.5249, 0.6524, 0.0000,  ..., 0.2278, 0.0000, 0.0000],
          ...,
          [0.0000, 0.0000, 0.0680,  ..., 0.4145, 1.3852, 0.5899],
          [0.0000, 0.7501, 0.0000,  ..., 1.1865, 0.0000, 0.1930],
          [1.5975, 0.8317, 0.0000,  ..., 1.4813, 0.0000, 0.7975]],

         [[0.3647, 2.4109, 0.0000,  ..., 0.0000, 0.0000, 0.7405],
          [1.5614, 0.0000, 0.2256,  ..., 0.0000, 0.1306, 0.0000],
          [0.0000, 0.7633, 1.0165,  ..., 1.6561, 0.0000, 0.0000],
          ...,
          [1.2564, 0.7591, 0.0000,  ..., 1.2792, 0.6227, 0.2759],
          [2.0884, 0.8001, 2.0372,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 1.2534, 0.0000]],

         [[0.1355, 0.6789, 0.0000,  ..., 0.0000, 0.0000, 0.0066],
          [0.0000, 0.0000, 0.5959,  ..., 0.0000, 0.0000, 0.1099],
          [0.0000, 0.3865, 0.0000,  ..., 1

In [4]:
# testing flatten

tensor = torch.rand(3 , 5, 6)

tensor_view = tensor.detach().clone().view(tensor.size(0), -1)
tensor_flatten = torch.flatten(tensor.detach().clone(), 1)

#print('tensor:', tensor)
#print('tensor_view:', tensor_view)
print('tensor view size:', tensor_view.size())
print('tensor flatten size:', tensor_flatten.size())
#print('tensor_flatten:', tensor_flatten)
print(tensor_view == tensor_flatten)

tensor view size: torch.Size([3, 30])
tensor flatten size: torch.Size([3, 30])
tensor([[True, True, True, True, True, True, True, True, True, True, True, True,
         True, True, True, True, True, True, True, True, True, True, True, True,
         True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True, True, True,
         True, True, True, True, True, True, True, True, True, True, True, True,
         True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True, True, True,
         True, True, True, True, True, True, True, True, True, True, True, True,
         True, True, True, True, True, True]])


In [5]:
# InceptionAux 
# Default tensor dimension used in InceptionAux
# batch x depth x height x width
tensor = torch.rand(2, 768, 299, 299)
# inceptionv3Cutie.InceptionAux(in_channels, num_channels)
inceptionAux = inceptionv3Cutie.InceptionAux(768, 1000)
inceptionAux = inceptionAux(tensor)

print(inceptionAux)

tensor([[ 0.2105,  0.1404, -0.3234,  ..., -0.5106, -0.2216,  0.1174],
        [ 0.2176,  0.1410, -0.3217,  ..., -0.5121, -0.2170,  0.1291]],
       grad_fn=<AddmmBackward0>)


In [6]:
# InceptionE 
# Default tensor dimension used in InceptionE
# batch x depth x height x width
tensor = torch.rand(2, 2048, 299, 299)
# inceptionv3Cutie.InceptionE(in_channels)
inceptionE = inceptionv3Cutie.InceptionE(2048)
inceptionE = inceptionE(tensor.detach().clone())

print(inceptionE)

tensor([[[[0.6151, 0.0000, 0.0000,  ..., 1.5338, 0.5687, 0.3768],
          [0.3014, 1.3115, 0.0000,  ..., 0.0000, 0.0376, 1.8037],
          [0.0000, 0.0000, 0.0000,  ..., 0.7673, 0.1753, 0.0000],
          ...,
          [0.0989, 0.0000, 0.2057,  ..., 0.4844, 0.0000, 1.3135],
          [0.1835, 0.3896, 0.9302,  ..., 2.2339, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.8607,  ..., 0.0000, 2.1668, 0.0000]],

         [[0.6588, 0.7134, 1.8324,  ..., 1.0867, 0.0000, 0.1773],
          [0.0000, 0.0000, 3.7024,  ..., 0.0000, 0.8423, 0.0000],
          [0.0000, 0.7715, 0.0000,  ..., 0.3373, 0.2275, 0.3795],
          ...,
          [1.3672, 0.0000, 1.0275,  ..., 0.2902, 0.0000, 0.2532],
          [0.9876, 0.9944, 1.3485,  ..., 0.0000, 2.6862, 0.3946],
          [0.8344, 0.9150, 1.2431,  ..., 0.7862, 0.5747, 0.0000]],

         [[0.9164, 0.0000, 0.0000,  ..., 0.0000, 0.8959, 0.0000],
          [0.0000, 0.3880, 0.0000,  ..., 0.0586, 0.0000, 1.2982],
          [0.0000, 0.0000, 0.2434,  ..., 0

In [7]:
# InceptionD 
# Default tensor dimension used in InceptionD
# batch x depth x height x width
tensor = torch.rand(2, 768, 299, 299)
# inceptionv3Cutie.InceptionD(in_channels)
inceptionD = inceptionv3Cutie.InceptionD(768)
inceptionD = inceptionD(tensor.detach().clone())

print(inceptionD)

tensor([[[[0.6871, 0.0000, 0.0000,  ..., 0.8128, 0.0000, 0.0000],
          [1.0656, 1.1801, 0.5477,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0031, 0.0000,  ..., 1.3922, 0.0000, 0.0000],
          ...,
          [0.8718, 0.7021, 0.9793,  ..., 0.0000, 0.0000, 0.0000],
          [0.2063, 0.4113, 1.1109,  ..., 1.2329, 0.0000, 0.0000],
          [0.0738, 0.0000, 0.0000,  ..., 0.6681, 1.3512, 0.0000]],

         [[1.0884, 0.6699, 0.0000,  ..., 0.3700, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.2943,  ..., 0.2633, 0.0000, 1.3778],
          [0.0000, 0.5958, 0.0054,  ..., 0.2840, 1.2155, 0.0000],
          ...,
          [1.0699, 0.8023, 0.0000,  ..., 0.2766, 0.0000, 0.0000],
          [1.4989, 0.2231, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.1773, 0.0000, 0.0000]],

         [[0.0000, 0.0000, 0.0000,  ..., 0.6011, 0.1348, 0.0000],
          [1.5812, 0.2978, 0.8582,  ..., 0.2900, 0.0000, 0.1268],
          [0.2653, 0.4999, 0.9170,  ..., 0

In [8]:
# InceptionC 
# Default tensor dimension used in InceptionC
# batch x depth x height x width
tensor = torch.rand(2, 768, 299, 299)
# inceptionv3Cutie.InceptionC(in_channels)
inceptionC = inceptionv3Cutie.InceptionC(768, channels_7x7=128)
inceptionC = inceptionC(tensor.detach().clone())

print(inceptionC)

tensor([[[[9.5139e-01, 0.0000e+00, 0.0000e+00,  ..., 6.7409e-01,
           0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 0.0000e+00],
          [2.8095e-01, 0.0000e+00, 0.0000e+00,  ..., 2.7411e-01,
           5.3743e-02, 0.0000e+00],
          ...,
          [4.4772e-01, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           0.0000e+00, 6.6902e-01],
          [0.0000e+00, 0.0000e+00, 9.4728e-01,  ..., 8.6171e-01,
           1.1595e+00, 1.8410e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 6.9909e-01,
           0.0000e+00, 0.0000e+00]],

         [[9.4835e-01, 2.7339e+00, 8.1178e-01,  ..., 1.0022e+00,
           1.1061e+00, 3.6681e-01],
          [5.7941e-01, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           1.7887e-01, 1.6550e+00],
          [2.6441e+00, 6.9003e-01, 0.0000e+00,  ..., 0.0000e+00,
           7.7760e-01, 7.2697e-01],
          ...,
          [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 1.7300

In [9]:
# InceptionB 
# Default tensor dimension used in InceptionB
# batch x depth x height x width
tensor = torch.rand(4, 288, 299, 299)
# inceptionv3Cutie.InceptionB(in_channels)
inceptionB = inceptionv3Cutie.InceptionB(288)
inceptionB = inceptionB(tensor.detach().clone())

print(inceptionB)

tensor([[[[6.1200e-01, 0.0000e+00, 0.0000e+00,  ..., 1.7957e+00,
           6.6941e-01, 0.0000e+00],
          [1.2354e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           5.5804e-01, 0.0000e+00],
          [1.6085e+00, 2.3798e-01, 0.0000e+00,  ..., 0.0000e+00,
           5.1175e-01, 3.4561e-01],
          ...,
          [8.9859e-02, 3.9836e-01, 1.5321e+00,  ..., 1.9369e+00,
           1.0924e+00, 1.9179e+00],
          [0.0000e+00, 0.0000e+00, 1.9597e-01,  ..., 2.0592e+00,
           0.0000e+00, 4.1860e-01],
          [0.0000e+00, 0.0000e+00, 1.3084e+00,  ..., 4.4142e-02,
           0.0000e+00, 1.1796e+00]],

         [[5.3935e-01, 0.0000e+00, 6.6510e-01,  ..., 0.0000e+00,
           8.1372e-01, 0.0000e+00],
          [8.7826e-01, 4.1583e-01, 5.2703e-01,  ..., 3.0814e-01,
           3.5989e-01, 1.5417e+00],
          [1.1599e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
           5.5782e-01, 0.0000e+00],
          ...,
          [4.9240e-01, 0.0000e+00, 0.0000e+00,  ..., 1.9476

In [10]:
# InceptionA 
# Default tensor dimension used in InceptionA
# batch x depth x height x width
tensor = torch.rand(4, 192, 299, 299)
# inceptionv3Cutie.InceptionA(in_channels)
inceptionA = inceptionv3Cutie.InceptionA(192, pool_features=32)
inceptionA = inceptionA(tensor.detach().clone())

print(inceptionA)

tensor([[[[0.3769, 0.0000, 0.0000,  ..., 0.7351, 0.0886, 0.6161],
          [0.7053, 0.6381, 0.0000,  ..., 0.3070, 0.7869, 0.0000],
          [0.0000, 0.0000, 0.9401,  ..., 0.0633, 0.0000, 0.0000],
          ...,
          [0.5529, 0.6940, 0.1017,  ..., 1.3358, 0.0000, 0.0000],
          [0.0000, 0.0997, 0.0000,  ..., 0.8674, 0.0000, 0.0000],
          [0.8593, 0.0000, 0.5909,  ..., 0.0130, 0.0000, 0.0000]],

         [[0.0000, 0.2362, 0.0000,  ..., 1.4299, 0.0000, 0.5126],
          [0.3420, 0.9902, 0.0000,  ..., 0.0000, 0.2564, 0.5188],
          [1.0331, 0.0000, 0.0000,  ..., 0.0000, 1.4682, 0.8143],
          ...,
          [0.4863, 0.0000, 0.2026,  ..., 0.0000, 0.0000, 0.0000],
          [0.1086, 0.2046, 1.2637,  ..., 0.0000, 0.0896, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 1.4202, 0.4006, 0.5697]],

         [[1.8409, 0.0000, 0.8655,  ..., 0.0000, 0.5581, 1.2833],
          [0.2079, 0.0000, 0.2960,  ..., 0.0513, 0.7371, 0.0438],
          [0.4389, 0.0000, 0.0868,  ..., 0

In [11]:
# Inception3 
# Default tensor dimension used in Inception3
# batch x depth x height x width
tensor = torch.rand(2, 3, 299, 299)
# inceptionv3Cutie.Inception3()
inception3 = inceptionv3Cutie.Inception3(num_classes=2)
inception3 = inception3(tensor.detach().clone())

print(inception3)
print(inception3[0].size())


(tensor([[0.9858, 0.7291, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.6104, 0.0000, 0.8882,  ..., 0.0000, 0.0000, 0.9788]],
       grad_fn=<ViewBackward0>), tensor([[ 0.0009,  0.0177],
        [-0.0243,  0.0282]], grad_fn=<AddmmBackward0>))
torch.Size([2, 2048])


In [12]:
# Inception3 (Pretrained)
# Default tensor dimension used in Inception3
# batch x depth x height x width
tensor = torch.rand(2, 3, 299, 299)
# inceptionv3Cutie.Inception3()
pretrainedInception3 = inceptionv3Cutie.customInception3(pretrained=True, aux_logits=False)
pretrainedInception3 = pretrainedInception3(tensor.detach().clone())

print(pretrainedInception3)
print(pretrainedInception3.size())

Inception v3 pretraining: Hardcoded strict=False, Might be omiting layers
tensor([[0.4612, 0.0000, 0.0000,  ..., 0.9115, 0.0000, 0.0000],
        [0.0000, 0.6714, 0.0000,  ..., 0.6067, 0.0000, 0.0000]],
       grad_fn=<ViewBackward0>)
torch.Size([2, 2048])


In [13]:
print(pretrainedInception3[0])

tensor([0.4612, 0.0000, 0.0000,  ..., 0.9115, 0.0000, 0.0000],
       grad_fn=<SelectBackward0>)
